/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sccsbt.rede;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas.Almeida
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonIngest = new javax.swing.JRadioButton();
        buttonAprovacao = new javax.swing.JRadioButton();
        buttonOk = new javax.swing.JRadioButton();
        buttonPlayout = new javax.swing.JRadioButton();
        buttonOff = new javax.swing.JRadioButton();
        buttonGravados = new javax.swing.JRadioButton();
        buttonMapear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 370));
        setPreferredSize(new java.awt.Dimension(450, 370));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione as pastas compartilhadas que você deseja:");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        buttonIngest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonIngest.setText("INGEST");
        buttonIngest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIngestActionPerformed(evt);
            }
        });

        buttonAprovacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAprovacao.setText("Análise Aprovação");
        buttonAprovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAprovacaoActionPerformed(evt);
            }
        });

        buttonOk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonOk.setText("Análise ok");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonPlayout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonPlayout.setText("Playout");
        buttonPlayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayoutActionPerformed(evt);
            }
        });

        buttonOff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonOff.setText("Sala de off");
        buttonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOffActionPerformed(evt);
            }
        });

        buttonGravados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonGravados.setText("Switch Gravados");
        buttonGravados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGravadosActionPerformed(evt);
            }
        });

        buttonMapear.setText("Mapear");
        buttonMapear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMapearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonIngest)
                            .addComponent(buttonOk)
                            .addComponent(buttonPlayout)
                            .addComponent(buttonOff))
                        .addGap(15, 15, 15)
                        .addComponent(buttonMapear))
                    .addComponent(buttonAprovacao)
                    .addComponent(buttonGravados))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonIngest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAprovacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPlayout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGravados)
                .addGap(33, 33, 33)
                .addComponent(buttonMapear)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIngestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIngestActionPerformed
       
    }//GEN-LAST:event_buttonIngestActionPerformed

    private void buttonAprovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAprovacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAprovacaoActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonPlayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlayoutActionPerformed

    private void buttonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOffActionPerformed

    private void buttonGravadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGravadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGravadosActionPerformed

    private void buttonMapearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMapearActionPerformed
        ArrayList selected = new ArrayList();
        if (buttonIngest.isSelected()){
            selected.add("Ingest");
        }
        if (buttonAprovacao.isSelected()){
            selected.add("Aprovacao");
        }
        if (buttonOk.isSelected()){
            selected.add("Ok");
        }
        if (buttonPlayout.isSelected()){
            selected.add("Playout");
        }
        if (buttonOff.isSelected()){
            selected.add("Off");
        }
        if (buttonGravados.isSelected()){
            selected.add("Gravados");
        }
        Service service = new Service(selected);
        String resultado = service.mapearRede(selected);
        
        JOptionPane.showMessageDialog(null, resultado, "Resultado do Mapeamento", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonMapearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttonAprovacao;
    private javax.swing.JRadioButton buttonGravados;
    private javax.swing.JRadioButton buttonIngest;
    private javax.swing.JButton buttonMapear;
    private javax.swing.JRadioButton buttonOff;
    private javax.swing.JRadioButton buttonOk;
    private javax.swing.JRadioButton buttonPlayout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
